# 忽略编译警告信息
ignore-warning: []
# 脚本路径
script-folders:
  - 'scripts'
# 脚本构建产物缓存路径
script-build-folder: "scripts/.build"
# 预热语句
preheat-statement: |-
  println("[Artifex] Preheat done (${System.currentTimeMillis() - time}ms)! For help, type \"art\"")